export const FETCH_DATA = 'fetch_data'
export const INITIALIZE = 'initialize'
export const CHART_WEEK = 'chart_week'
export const CHART_MONTH = 'chart_month'
export const CHART_ALL_TIME = 'chart_all_time'
export const LEADERBOARD = 'leaderboard'
